# -----------------------------------------------------------------------------
# Gisst - developer task runner. All Python tooling goes through uv.
# -----------------------------------------------------------------------------

# Use bash for recipe execution so we get sane error handling.
SHELL := /usr/bin/env bash

IMAGE ?= gisst:latest

.DEFAULT_GOAL := help

.PHONY: help install run dev test lint format typecheck migrate revision \
        docker-build clean

help: ## Show this help.
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

install: ## Sync the project + dev dependencies into the venv.
	uv sync --extra dev

run: ## Run the app (Telegram bot + scheduler + API).
	uv run python -m gisst

dev: ## Run the app in dev mode (verbose logging).
	GISST_ENV=dev LOG_LEVEL=DEBUG uv run python -m gisst

test: ## Run the test suite.
	uv run pytest

lint: ## Lint with ruff.
	uv run ruff check .

format: ## Auto-format with ruff.
	uv run ruff format .

typecheck: ## Static type-check with mypy.
	uv run mypy

migrate: ## Apply all pending Alembic migrations.
	uv run alembic upgrade head

revision: ## Create a new autogenerated migration. Usage: make revision m="message"
	uv run alembic revision --autogenerate -m "$(m)"

docker-build: ## Build the container image.
	docker build -t $(IMAGE) .

clean: ## Remove caches and build artifacts.
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage coverage.xml htmlcov \
		build dist src/*.egg-info
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
